apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlapp
spec:
  selector:
    matchLabels:
      app: rlapp
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: rlapp
        tier: backend
        track: stable
    spec:
      containers:
      - name: rlapp
        image: 976324526436.dkr.ecr.us-east-1.amazonaws.com/rlapp
        ports:
        - name: tcp
          containerPort: 5000
        imagePullPolicy: IfNotPresent
        # command:
        # - python
        # - app.py
      # nodeSelector:
      #   beta.kubernetes.io/os: windows
---
apiVersion: v1
kind: Service
metadata:
  name: rlapp-service
  namespace: default
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: rlapp
    tier: backend
    track: stable
  sessionAffinity: None
  type: LoadBalancer